### ISSUE TITLE
Have you test deep_gcns on ppi dataset?

### ISSUE THREAD

**Issue by wjlpku** [lightaime/deep_gcns#11]
Hi, I have found this method is STOA of Deep GCN, and I find it has great performance on ppi dataset, [https://paperswithcode.com/sota/node-classification-on-ppi](url), but I can not find the code about ppi dataset, can anyone tell me about this?

**Comment by lightaime** [comment]
We implement it using our pytorch version. Please check it here: https://github.com/lightaime/deep_gcns_torch/tree/master/examples/ppi

**Comment by wjlpku** [comment]
Thanks for your reply, I will try it.
