### ISSUE TITLE
h5 dataset generation script

### ISSUE THREAD

**Issue by anderiri2** [lightaime/deep_gcns#12]
Hi @lightaime, could you please provide the script to generate the .h5 dataset?
Thanks in advance, Ander.

**Comment by lightaime** [comment]
Hi Ander, the script is provided here now. https://github.com/lightaime/deep_gcns/blob/master/sem_seg/gen_indoor3d_h5.py 

To prepare your own HDF5 data, please first download the 3D indoor parsing dataset and use 
`python collect_indoor3d_data.py` to re-organize and then use `python gen_indoor3d_h5.py` to generate HDF5 files.

**Comment by anderiri2** [comment]
Thank you very much!
