### ISSUE TITLE
why the inpus_ph default to shape=(batch_size, num_vertices, 9)?

### ISSUE THREAD

**Issue by zem007** [lightaime/deep_gcns#13]
Hi!
As your write in **_inputs_ph = tf.placeholder(tf.float32, shape=(batch_size, num_vertices, 9))_**.

Why it is default to 9? where is the **9** from? I think the 3D point cloud should be 3.

If I wish to use the model to my own point cloud dataset **with (x,y,z) coordinates => 3**， should I change the original code to shape=(batch_size, num_vertices, 3)?

thanks!

**Comment by lightaime** [comment]
Hi @zem007 ,

The data we used has 9 dimensional features including 3D for xyz coordinates, 3D for RGB color and 3D for normalized xyz coordinates. Sure, you can chage the input shape to (batch_size, num_vertices, 3) to make the model fit for your data.

**Comment by zem007** [comment]
> Hi @zem007 ,
> 
> The data we used has 9 dimensional features including 3D for xyz coordinates, 3D for RGB color and 3D for normalized xyz coordinates. Sure, you can chage the input shape to (batch_size, num_vertices, 3) to make the model fit for your data.

thanks! It works well in my own dataset.
