### ISSUE TITLE
Graph convolution

### ISSUE THREAD

**Issue by Ericjiejie** [lightaime/deep_gcns#15]
hi, @lightaime
I'm a beginner  in GCN. In many papers, I see that GCN has a graph Laplacian matrix, but you don't seem to use it. How do you implement graph convolution?

**Comment by lightaime** [comment]
It is implemented in the framework of message passing like MPNN:
https://arxiv.org/pdf/1704.01212.pdf. Please check the paper for more
information.

**Comment by Ericjiejie** [comment]
Thanks for your advice.

**Comment by Ericjiejie** [comment]
I have another question. If the input is not point clouds, but a feature map. Can I use your network by adjusting the network?

**Comment by Ericjiejie** [comment]
I have another question. If the input is not point clouds, but feature maps. Can I use your network by adjusting the network?

**Comment by lightaime** [comment]
Hi,

For sure, you can treat each pixel as a point then use whatever have been
developed in point cloud. You can also figure better graph representation
depending on your task.

**Comment by Ericjiejie** [comment]
For example, for two RGB images with 64 pixels in width and height, I change the tensor to (2, 3, 4096, 1) in torch.Is that true?Is there such a distance metric  to satisfy  feature distance calculation because the feature is the pixel value rather than the XYZ spatial coordinates.

**Comment by lightaime** [comment]
Yes, you are right. As for the distance metric, it depends on your problem.
I suggest you try some things like L2 distance or Cos Similarity.

**Comment by Ericjiejie** [comment]
Thank you for your answer, I have one last question.
I don't use knn to find neighbor nodes (which can avoid distance calculation and the adjacency matrix is known), but use the adjacency matrix to implement graph convolution. Is this method possible? Specifically, for pose estimation task, I use ResGCN as the network structure, and use Y = σ(AXW) as the graph convolutional operation, where A is the normalizaton adjacency matrix and W is the weight of the convolutional layer. Of course, after doing this, the network cannot be too deep, because there is no Dynamic edge convolution which will cause over-smoothing. I want to know if my idea is feasible.

**Comment by lightaime** [comment]
I recommend you to try it out. You can build your convolution layer like Y
= σ(AXW) + X to alleviate the effect of vanishing gradient problem.

**Comment by Ericjiejie** [comment]
Yes, I want to try as you say.
Thanks.
