### ISSUE TITLE
Pytorch version?

### ISSUE THREAD

**Issue by MSC19950601** [lightaime/deep_gcns#3]
Is there a pytorch version? :)

**Comment by lightaime** [comment]
We have implemented the basic modules (Res, Dense and Dilation) using pytorch geometric. We will release pytorch codes soon. Stay tuned!

**Comment by amiltonwong** [comment]
Great! Looking forward to pytorch version

**Comment by MSC19950601** [comment]
Great! Looking forward to pytorch version

**Comment by guochengqian** [comment]
@MSC19950601 @amiltonwong  Hello, thanks for your interest in our work. The draft of Pytorch version Deep GCN is ready now. Please check our [https://github.com/lightaime/deep_gcns_torch](repo) and feel free to ask any question.
