### ISSUE TITLE
missing 'meta/anno_paths.txt'

### ISSUE THREAD

**Issue by guozhiyao** [lightaime/deep_gcns#7]
I download dataset and unzip into data/. And run the collect_indoor3d_data.py, it shows:
`
Traceback (most recent call last):
  File "collect_indoor3d_data.py", line 6, in <module>
    import indoor3d_util
  File "/deep_gcns/sem_seg/indoor3d_util.py", line 14, in <module>
    g_classes = [x.rstrip() for x in open(os.path.join(BASE_DIR, 'meta/class_names.txt'))]
FileNotFoundError: [Errno 2] No such file or directory: '/deep_gcns/sem_seg/meta/class_names.txt'
`

**Comment by lightaime** [comment]
Sorry, I did not upload the meta files by mistake. I just uploaded it. Can you `git pull` and try again?
