### ISSUE TITLE
the obj file can not open

### ISSUE THREAD

**Issue by wangziningabc** [lightaime/deep_gcns#8]
i got the prediction visualization file and the groudtruth file,but i can not open them with maya or 3D Max,my process of achieve files as follows
    python batch_inference.py --model_path log/epoch_30.ckpt --dump_dir log/dump -- 
    output_filelist log/output_filelist.txt --room_data_filelist meta/area5_data_label.txt --visu
and the epoch_30.ckpt is acquired through training the S3DIS dataset
the zip package is the obj files(_gt,_pred)，hope you can help me ,thanks a lot! 
[dump.zip](https://github.com/lightaime/deep_gcns/files/3475045/dump.zip)

**Comment by lightaime** [comment]
We will open source our visualization code soon. I hope that will help you.

**Comment by lightaime** [comment]
Hi @wangziningabc . Our visualization codes are available now. See https://github.com/lightaime/deep_gcns/blob/master/sem_seg/visualization.ipynb for the details. Hopefully, this will solve your problem.

**Comment by wangziningabc** [comment]
Thank you for your help@lightaime
