### ISSUE TITLE
 No such file or directory: 'pretrained/ResGCN-28/log5/output_filelist.txt'

### ISSUE THREAD

**Issue by yestinl** [lightaime/deep_gcns#9]
missing file

**Comment by yestinl** [comment]
(py36) longyanxin@sdcs-dl-09:/media/Disk/longyanxin/deep_gcns-master/sem_seg$ sh +x test_pretrained.sh

Processing Model pretrained/ResGCN-28

/home/longyanxin/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/longyanxin/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/longyanxin/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/longyanxin/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:461: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/longyanxin/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:462: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/longyanxin/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:465: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "batch_inference.py", line 13, in <module>
    import indoor3d_util
  File "/media/Disk/longyanxin/deep_gcns-master/sem_seg/indoor3d_util.py", line 14, in <module>
    g_classes = [x.rstrip() for x in open(os.path.join(BASE_DIR, 'meta/class_names.txt'))]
FileNotFoundError: [Errno 2] No such file or directory: '/media/Disk/longyanxin/deep_gcns-master/sem_seg/meta/class_names.txt'

Evaluating Model pretrained/ResGCN-28

Namespace(area=5, folder='pretrained/ResGCN-28', num_classes=13, path='')
Area:  5
Traceback (most recent call last):
  File "eval_iou_accuracy.py", line 33, in <module>
    pred_data_label_filenames += [os.path.join(PATH, line.rstrip()) for line in open(file_name)]
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/ResGCN-28/log5/output_filelist.txt'

**Comment by lightaime** [comment]
Hi yestinl. Can you pull and try it again. I guess this is because the meta files are missing.
